# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: hello-world

channels:
  - memfault
  - conda-forge
  - defaults
dependencies:
  - gcc=12.2.0
  - gdb=12.1
  - ninja=1.11.0
  - cmake=3.23.3
  - python=3.10.5
  - pip=22.2.1
  - libprotobuf=3.20.1
  - pip:
    - protobuf==3.20.1

